# Uncomment the next line to define a global platform for your project
source "https://github.com/CocoaPods/Specs.git"

platform :ios, "9.0"
use_frameworks!

target "TestDriver" do
  rn_path = "../node_modules/react-native"

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod "yoga", path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod "React", path: rn_path, subspecs: [
    "Core",
    "CxxBridge",
    "DevSupport",
    "RCTActionSheet",
    "RCTAnimation",
    "RCTGeolocation",
    "RCTImage",
    "RCTLinkingIOS",
    "RCTNetwork",
    "RCTSettings",
    "RCTText",
    "RCTVibration",
    "RCTWebSocket",
  ]

  # React Native third party dependencies podspecs
  pod "DoubleConversion", :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod "glog", :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod "Folly", :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  pod "react-native-heap", path: "../node_modules/@heap/react-native-heap"

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target "TestDriverTests" do
    inherit! :search_paths
  end
end

# Force react-native-heap to be built as a static framework.
# Based on comments at https://github.com/CocoaPods/CocoaPods/issues/7428 .
pre_install do |installer|
    pod = installer.pod_targets.find { |p| p.name == 'react-native-heap'}
    def pod.static_framework?
        true
    end
end
